default: &default
  adapter: postgresql
  encoding: unicode
  database: zode64
  pool: 5
  username: zode64
  password:

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default

development:
  <<: *default
